# Application manifest for microservice deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/your-org/microservice.git
    targetRevision: HEAD
    path: /kubernetes
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
